ctlevent.js, index.html, lib/jquery.simplePagination.js, lib/simplePagination.css, list.js
Next step: connect the pagination widget to the event rendering.
=> Add pagination library

list.js
This commit swaps out the list for a map in prep for lunr.js (or other
JS library). It also replaces some inline functionality for a helper
function to inialize the page.
=> Replace event list with map.

index.html, lib/simplePagination.css, list.js
I changed the eventMap to an array so I could iterate through it
reliably - if necessary later we can always change this back to a Map
but it didn't seem to be necessary at this point.
=> Connect paginator to event list

list.js
This PR:
- redraws pagination to match the corresponding number of search results
- returns all search results when the text box returns to empty
=> Paginate search

events-manager.js, main.js
=> Move arrays containing all events, and filtered events to events manager

ctlevent.js, tests/test-ctlevent.js, tests/test-utils.js, utils.js
This PR refactors how events build up an array of associated properties, and how they're printed out.
=> Property array

main.js, package.json, tests/test-utils.js, utils.js
This PR adds functions to set and remove query string parameters from the URL.
=> Url params

main.js
This commit splits the date string from the date picker, and constructs
a date object.  Removes hard-coded time/time-zone string.
=> Date constructor - PMT #110477

main.js, utils.js
This commit breaks out URL parameter filtering into three functions:
- readURLParams()
- filterOnURLParams()
- populateURLParams()
=> Breakdown URL param filtering

list.css, main.js
=> better filter widget ui

package.json
Closes #35
https://greenkeeper.io/
=> fix(package): update lunr to version 2.0.2

ctlevent.js, tests/test-ctlevent.js
Swap in "Graduate Student" to better reflect the audience for events.
=> "Student" to "Graduate Student" PMT# 110783

ctlevent.js, tests/test-utils.js, utils.js
This commit sets up some regexes to snip off the room number from event
locations.
=> Handle room numbers PMT#110780

ctlevent.js, list.css, package.json
=> Room number styling

events-manager.js, list.css, main.js, tests/test-utils.js
=> new widget chrome

ctlevent.js, list.css
WRT: https://github.com/ccnmtl/calendar-widget/pull/61
=> Remove unnecessary <br/>'s; add pointer to reg button

tests/test-utils.js, utils.js
This sets up a single event view for use in building a sitemap that
would include current events on the calendar.
=> Implements single event view PMT #111365

ctlevent.js, main.js, tests/test-utils.js, utils.js
This commit implements a function that sorts events by increasing date.
It also stubs in a Date constructor, which needs to be refactored to not
use the string form of the constructor.
=> Write tests and implement a sort function.

ctlevent.js, list.css
=> Layout updates

ctlevent.js, tests/test-ctlevent.js
This commit prints the day of the week when events are rendered. It also
removes some un-needed fields on the event object.
=> Display Day of Week, PMT#: 111908

.gitignore, main.js, tests/test-utils.js, utils.js
This commit introduces a new validation function. This function validates that
the dates given are within a given range. For now, it just prints a
message to the console when a date range doesn't pass validation.
=> Filter refactor

tests/test-utils.js, utils.js
This commit removes kind of kludgey date comparison that depended on
milliseconds from the epoch. This switches back to using the comparitor
of the Date object. It standarizes the the times of of the Date objects
passed in: start dates are set for midnight of that day, and end dates
are set for 23:59 of that day.
=> Refactor validate function

lib/simplePagination.css, list.css
=> Fix buttons

homepage.html, index.html, src/js/homepage.js, webpack.config.js
This commit adds a second entrypoint in the Webpack config. It builds out the homepage feed in separate js file.
=> PMT #116019: Refactor Homepage feed to use Webpack

README.md, src/css/list.css, src/js/main.js
Search and Clear button functionality added. Tweaked styling to reduce unused space.
=> Noresults bug

package-lock.json, src/css/list.css, src/js/ctlevent.js
This commit:
* Implements date ranges for the home page and calendar page widgets
* Underlines the title text so it's perceivable
* Adds button CTA to each event so that events that use Qualtrics for
registration will also nudge users to Bedeworks
=> CW-528 Add date ranges to calendar widgets

src/css/list.css, src/js/ctlevent.js, src/js/main.js
* Heading added above search 
* Buttons have been changed to look the same. 
* Small spacing changes
* Results for tag will now show all search terms
* If the ending time and starting time are the same, will only show one time.
=> Spacing issues

src/js/ctlevent.js, src/js/main.js
* This PR addresses the issue where some events weren't displaying a multiday range.
* Some light lint fixes.
=> fixes date range bug

package-lock.json, package.json
=> Revert webpack-dev-server to 3.11.2

package-lock.json, package.json
Reverts ccnmtl/calendar-widget#629
=> Revert "Bump style-loader from 3.3.1 to 4.0.0"
